.TH ipinfo 1 "November 2023" "ipinfo"

.SH NAME
ipinfo \- IP information lookup tool

.SH SYNOPSIS
.B ipinfo
[\fICOMMAND\fP] [\fIOPTIONS\fP] [\fIARGUMENTS\fP]

.SH DESCRIPTION
The
.B ipinfo
command is a versatile tool for retrieving information related to IP addresses, Autonomous System Numbers (ASNs), and various related operations. It provides detailed insights into IP addresses, ASN details, and offers a range of utilities for managing and analyzing IP-related information.

When invoked without any command or options, it provides a summary.

.SH COMMANDS
.TP 
.B <ip> 
Look up details for an IP address, e.g. 8.8.8.8.

.TP 
.B <asn>
Look up details for an ASN, e.g. AS123 or as123.

.TP
.B myip
Get details for your IP.

.TP
.B bulk
Get details for multiple IPs in bulk.

.TP
.B asn
Tools related to ASNs.

.TP
.B summarize
Get summarized data for a group of IPs.

.TP
.B map
Open a URL to a map showing the locations of a group of IPs.

.TP
.B prips
Print IP list from CIDR or range.

.TP
.B grepip
Grep for IPs matching criteria from any source.

.TP
.B matchip
Print the overlapping IPs and subnets.

.TP
.B grepdomain
Grep for domains matching criteria from any source.

.TP
.B cidr2range
Convert CIDRs to IP ranges.

.TP
.B cidr2ip
Convert CIDRs to individual IPs within those CIDRs.

.TP
.B range2cidr
Convert IP ranges to CIDRs.

.TP
.B range2ip
Convert IP ranges to individual IPs within those ranges.

.TP
.B randip
Generates random IPs.

.TP
.B splitcidr
Splits a larger CIDR into smaller CIDRs.

.TP
.B mmdb
Read, import, and export mmdb files.

.TP
.B calc
Evaluates a mathematical expression that may contain IP addresses.

.TP
.B tool
Misc. tools related to IPs, IP ranges, and CIDRs.

.TP
.B download
Download free ipinfo database files.

.TP
.B cache
Manage the cache.

.TP
.B config
Manage the config.

.TP
.B quota
Print the request quota of your account.

.TP
.B init
Login or signup account.

.TP
.B logout
Delete your current API token session.

.TP
.B completion
Install or output shell auto-completion script.

.TP
.B version
Show current version.

.SH OPTIONS

.TP
.B GENERAL OPTIONS:


.TP
.B --token <tok>, -t <tok>
Use <tok> as API token.

.TP
.B --nocache
Do not use the cache.

.TP
.B --version, -v
Show binary release number.

.TP
.B --help, -h
Show help.


.TP
.B OUTPUT OPTIONS:


.TP
.B --field <field>, -f <field>
Lookup only specific fields in the output.
Field names correspond to JSON keys, e.g. 'hostname' or 'company.type'.
Multiple field names must be separated by commas.

.TP
.B --nocolor
Disable colored output.


.TP
.B FORMAT OPTIONS:


.TP
.B --pretty, -p
Output pretty format.

.TP
.B --json, -j
Output JSON format.

.TP
.B --csv, -c
Output CSV format.

.TP
.B --yaml, -y
Output YAML format.

.SH EXAMPLES
.TP
.B ipinfo myip
Get details for your IP.

.TP
.B ipinfo 8.8.8.8
Look up details for a specific ip address.

.TP
.B ipinfo
Get a summary regarding the command.

.TP
.B ipinfo grepdomain -n file.txt
Access subcommands through the main command.

.SH SEE ALSO
.BR ipinfo-asn (1),
.BR ipinfo-bulk (1).

.SH REPORTING BUGS
Report bugs to: https://github.com/ipinfo/cli/issues
